# Generated by Django 5.2.12 on 2026-03-04 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=128, verbose_name='name (eng)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_local',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='country',
            name='numeric_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='normalized_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='platform_api.geoplace', verbose_name='Overstructure geo place'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='timezone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='org',
            name='short_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='org',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='org',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
        migrations.AlterField(
            model_name='org',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name_en',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sport',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='venue',
            name='short_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='ts_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='ts_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated at'),
        ),
    ]
