# Generated by Django 5.2.12 on 2026-03-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0003_add_presence_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgpresence',
            options={'verbose_name_plural': 'Org-sport mappings'},
        ),
        migrations.AlterModelOptions(
            name='personpresence',
            options={'verbose_name_plural': 'Person-sport mappings'},
        ),
    ]
