# Generated by Django 5.2.12 on 2026-03-04 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0004_minor_meta_updates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditRequestsInbox",
            fields=[
                (
                    "ts_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "ts_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Org", "Org"),
                            ("Location", "Geo Place"),
                            ("Venue", "Venue"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("Merge", "Merge"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Duplicate", "Duplicate"),
                            ("Applied", "Applied"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("vertical_entity_id", models.UUIDField(blank=True, null=True)),
                (
                    "target_entity_id",
                    models.UUIDField(
                        blank=True,
                        help_text="NOTE: Only nullable for CREATE requests",
                        null=True,
                        verbose_name="Core entity target id",
                    ),
                ),
                ("payload", models.JSONField(help_text="Content of the request")),
                (
                    "ts_taken_in_charge",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Taken in charge at"
                    ),
                ),
                (
                    "ts_review_completed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed review at"
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edit_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "finalised_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="NOTE: not null with APPLIED status",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edit_requests_finalized",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Review closed by",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        db_column="sport_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbox_requests",
                        to="platform_api.sport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Edit requests inbox",
                "db_table": "edit_requests_inbox",
            },
        ),
        migrations.CreateModel(
            name="EditRequestsInboxEvent",
            fields=[
                (
                    "ts_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "ts_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Comment", "Comment"),
                            ("Reviewed", "Reviewed"),
                            ("Applied", "Applied"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edit_request_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="platform_api.editrequestsinbox",
                    ),
                ),
            ],
            options={
                "db_table": "edit_requests_inbox_event",
            },
        ),
        migrations.AddIndex(
            model_name="editrequestsinbox",
            index=models.Index(
                fields=["status", "entity_type"], name="ix_inbox_status_type"
            ),
        ),
        migrations.AddIndex(
            model_name="editrequestsinbox",
            index=models.Index(fields=["sport"], name="ix_inbox_sport"),
        ),
        migrations.AddIndex(
            model_name="editrequestsinbox",
            index=models.Index(fields=["target_entity_id"], name="ix_inbox_target"),
        ),
        migrations.AddIndex(
            model_name="editrequestsinbox",
            index=models.Index(
                fields=["vertical_entity_id"], name="ix_inbox_vertical_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="editrequestsinboxevent",
            index=models.Index(
                fields=["request", "event_type"], name="ix_inbox_event__req_type"
            ),
        ),
    ]
