# Generated by Django 5.2.12 on 2026-03-04 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0005_edit_requests_inbox_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequestsinbox',
            options={'verbose_name': 'edit request', 'verbose_name_plural': 'edit requests inbox'},
        ),
        migrations.AddConstraint(
            model_name='editrequestsinbox',
            constraint=models.CheckConstraint(condition=models.Q(('ts_review_completed__isnull', True), ('ts_taken_in_charge__isnull', True), ('ts_review_completed__gt', models.F('ts_taken_in_charge')), _connector='OR'), name='ck_inbox_review_completed_after_taken_in_charge'),
        ),
        migrations.AddConstraint(
            model_name='editrequestsinbox',
            constraint=models.CheckConstraint(condition=models.Q(('action', 'Create'), ('target_entity_id__isnull', False), _connector='OR'), name='ck_inbox_target_required_for_update_merge'),
        ),
    ]
