# Generated by Django 5.2.12 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0006_added_constraints_to_inbox_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequestsinbox',
            name='vertical_entity_id',
            field=models.UUIDField(),
        ),
    ]
