# Generated by Django 5.2.12 on 2026-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0008_major_review_to_inbox_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editrequestsinboxevent",
            name="notes",
        ),
        migrations.AddField(
            model_name="editrequestsinboxevent",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="editrequestsinboxevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("comment", "Comment"),
                    ("data_editing", "Data editing"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                    ("approved", "Approved"),
                    ("applied", "Applied"),
                ],
                max_length=32,
            ),
        ),
    ]
