# Generated by Django 5.2.12 on 2026-03-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0009_update_inboxevent_table_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editrequestsinbox',
            old_name='changelog',
            new_name='notes',
        ),
    ]
