# Generated by Django 5.2.12 on 2026-03-16 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0010_updated_inbox_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="editrequestsinbox",
            name="ref_request",
            field=models.ForeignKey(
                blank=True,
                help_text="NOTE: not null with DUPLICATE and MERGED stati",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_requests",
                to="platform_api.editrequestsinbox",
                verbose_name="Referenced request id",
            ),
        ),
        migrations.AlterField(
            model_name="editrequestsinbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                    ("applied", "Applied"),
                    ("merged", "Merged"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="editrequestsinboxevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("comment", "Comment"),
                    ("data_editing", "Data editing"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                    ("approved", "Approved"),
                    ("applied", "Applied"),
                    ("merged", "Merged"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="editrequestsinbox",
            index=models.Index(fields=["ref_request_id"], name="idx_inbox_ref_request"),
        ),
    ]
