# Generated by Django 5.2.12 on 2026-03-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0011_added_merge_to_inbox_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_create_target_null",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_noncreate_target_required",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_taken_fields_both_null_or_set",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_nonpending_requires_taken_fields",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_finalised_fields_both_null_or_set",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_applied_requires_finalised_fields",
        ),
        migrations.RemoveConstraint(
            model_name="editrequestsinbox",
            name="ck_inbox_nonapplied_finalised_fields_null",
        ),
    ]
