# Generated by Django 5.2.12 on 2026-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0012_removed_constraints_from_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ig',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wiki',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
