#!/usr/bin/env bash

ensure_sql_index_file() {
  info "Ensuring SQL index file exists"

  if [[ ! -f "$DB_INDEX_FILE" ]] || [[ ! -s "$DB_INDEX_FILE" ]]; then
    echo "-- generated by server/scripts/create_vertical.sh - do not edit" > "$DB_INDEX_FILE"
  fi
}

append_sql_index_entry() {
  info "Updating SQL index"

  if ! grep -Eq "^\\\i /db/verticals/${VERTICAL}\.sql$" "$DB_INDEX_FILE"; then
    echo "\i /db/verticals/${VERTICAL}.sql" >> "$DB_INDEX_FILE"
  else
    warn "SQL index already contains ${VERTICAL}.sql"
  fi
}

write_vertical_sql() {
  info "Writing ${VERTICAL}.sql bootstrap"
  render_vertical_sql > "$DB_GEN_FILE"
}

patch_docker_compose() {
  info "Patching docker-compose.dev.yml"

  if [[ ! -f "$COMPOSE_FILE" ]]; then
    warn "docker-compose file not found: $COMPOSE_FILE"
    return 0
  fi

  if grep -Eq "^\s*${VERTICAL}-api:" "$COMPOSE_FILE"; then
    warn "Service ${VERTICAL}-api already present in docker-compose"
    return 0
  fi

  local tmpfile
  local service_block
  tmpfile="$(mktemp)"
  service_block="$(render_service_block)"

  awk -v block="$service_block" '
    BEGIN { inserted=0 }
    /^networks:/ && inserted==0 {
      print block
      inserted=1
    }
    { print }
    END {
      if (inserted==0) {
        print ""
        print block
      }
    }
  ' "$COMPOSE_FILE" > "$tmpfile"

  mv "$tmpfile" "$COMPOSE_FILE"
}

patch_infra_files() {
  ensure_sql_index_file
  append_sql_index_entry
  write_vertical_sql
  patch_docker_compose
}