FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY ./platform /app/backend

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./shared/db_init.sh /app/db_init.sh
RUN chmod +x /app/db_init.sh

WORKDIR /app/backend
EXPOSE 8000

ENTRYPOINT ["/app/db_init.sh"]