"""smoke_autogen

Revision ID: 23c1ffc409ae
Revises: e7eea473be7b
Create Date: 2026-02-24 08:24:15.580045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23c1ffc409ae"
down_revision: Union[str, None] = "e7eea473be7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_variable",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_variable")
    # ### end Alembic commands ###
