"""main_platform_registries

Revision ID: 93f84a432e5d
Revises: 23c1ffc409ae
Create Date: 2026-02-24 13:40:31.727158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f84a432e5d'
down_revision: Union[str, None] = '23c1ffc409ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_orgs_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('parent_org_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_org_id'], ['app_orgs_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_orgs_registry_display_name'), 'app_orgs_registry', ['display_name'], unique=False)
    op.create_index(op.f('ix_app_orgs_registry_key'), 'app_orgs_registry', ['key'], unique=False)
    op.create_table('app_sports_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_org_sport_presence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('sport_local_ref', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['app_orgs_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['app_sports_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'sport_id', name='uq__app_org_sport_presence__org__sport')
    )
    op.create_index(op.f('ix_app_org_sport_presence_org_id'), 'app_org_sport_presence', ['org_id'], unique=False)
    op.create_index(op.f('ix_app_org_sport_presence_sport_id'), 'app_org_sport_presence', ['sport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_org_sport_presence_sport_id'), table_name='app_org_sport_presence')
    op.drop_index(op.f('ix_app_org_sport_presence_org_id'), table_name='app_org_sport_presence')
    op.drop_table('app_org_sport_presence')
    op.drop_table('app_sports_registry')
    op.drop_index(op.f('ix_app_orgs_registry_key'), table_name='app_orgs_registry')
    op.drop_index(op.f('ix_app_orgs_registry_display_name'), table_name='app_orgs_registry')
    op.drop_table('app_orgs_registry')
    # ### end Alembic commands ###
